### ISSUE TITLE
Gallery and Join Us buttons don't work on the nav bar

### ISSUE THREAD

**Issue by gnsharma** [PyJaipur/pyjaipur.github.io#4]
System Config:-

MacOs Mojave
Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Browser: Firefox 62.0.2 (64-bit)

Issue:- Clicking on Gallery button or Join us button in the nav bar doesn't do anything.

**Comment by gnsharma** [comment]
I looked into the issue. Most likely it is because of `_tg_upcomingeventcounter.countdown` in the next event counter section, as both chrome and firefox console complain that it is not a function.

**Comment by gnsharma** [comment]
I would have pushed a fix for this. However i am on vacation for the next 5 days. Just wanted to make sure that the issue is known.

**Comment by rishabhKalakoti** [comment]
The links are not working again.
Gallery, Join us and Blog.
